Repository jenkins-x/jx-api, pull requests merged in 2020-12, with the labels that each got.

#91 feat: add load requirements func with no defaults so we can handle jx gitops requirements merge nicely
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, size/S

#93 refactor: lets use the new jx-helper GetClusterRequirementsConfig function
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
Labels: approved, size/M

#95 feat: added in config to record Azure Key Vault Name
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, lgtm, ok-to-test, size/XS

#94 fix: AzureDNSConfig was incorrectly promoted field rather than nested
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, lgtm, ok-to-test, size/XS
