Repository jenkins-x/jx-api, pull requests merged in 2020-06, with the labels that each got.

#9 chore: added generated docs
  .gitignore
  docs/apidocs/includes/.html
  docs/apidocs/includes/_definitions.html
  docs/apidocs/includes/_oldversions.html
  docs/apidocs/includes/_overview.html
  docs/apidocs/includes/apps.html
  docs/apidocs/includes/pipelines.html
  docs/apidocs/includes/user_management.html
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  docs/apidocs/static/stylesheet.css
  docs/apidocs/static_includes/_definitions.html
  docs/apidocs/static_includes/_oldversions.html
  docs/apidocs/static_includes/_overview.html
  docs/apidocs/static_includes/apps.html
  docs/apidocs/static_includes/pipelines.html
  docs/apidocs/static_includes/user_management.html
  docs/configdocs/config.json
  docs/configdocs/templates/.gitignore
  docs/configdocs/templates/members.tpl
  docs/configdocs/templates/pkg.tpl
  docs/configdocs/templates/type.tpl
  docs/refdocs/config.json
  docs/refdocs/templates/.gitignore
  docs/refdocs/templates/members.tpl
  docs/refdocs/templates/pkg.tpl
  docs/refdocs/templates/type.tpl
Labels: size/XXL

#11 chore: generate openapi spec
  Makefile.codegen
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  pkg/client/openapi/all/openapi_generated.go
  pkg/client/openapi/core/openapi_generated.go
  pkg/client/openapi/k8s_io_api_batch_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_api_core_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_api_rbac_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_intstr_unversioned/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_meta_v1/openapi_generated.go
  pkg/client/openapi/k8s_io_apimachinery_resource_unversioned/openapi_generated.go
  pkg/client/openapi/schema_writer_generated.go
Labels: size/XXL

#13 chore: added initial docs
  README.md
Labels: size/M

#24 chore: improved linters on project
  hack/linter.sh
  pkg/apis/jenkins.io/v1/types_extensions.go
  pkg/config/install_requirements.go
  pkg/util/commands_test.go
  pkg/util/urls.go
Labels: approved, lgtm, size/L

#25 fix: replace jx dependency
  pkg/util/json/patch_test.go
Labels: approved, lgtm, size/XS

#26 fix: remove build unit annotation
  pkg/client/clientset/versioned/typed/jenkins.io/v1/buildpack_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/commitstatus_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environment_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/environmentrolebinding_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/extension_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fact_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/gitservice_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelineactivity_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/pipelinestructure_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/plugin_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/release_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/sourcerepository_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/team_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/testutil.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/user_expansion_test.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/workflow_expansion_test.go
  pkg/util/json/patch_test.go
Labels: approved, lgtm, size/L

#27 chore: move linter config into file
  .golangci.yml
  cmd/codegen/app/generate_clientset.go
  cmd/codegen/app/generate_docs.go
  cmd/codegen/app/generate_openapi.go
  cmd/codegen/app/generate_options.go
  cmd/codegen/app/root.go
  cmd/codegen/generator/client_set.go
  cmd/codegen/generator/common.go
  cmd/codegen/generator/docs.go
  cmd/codegen/generator/open_api.go
  cmd/codegen/util/commands.go
  cmd/codegen/util/files.go
  cmd/codegen/util/go.go
  cmd/codegen/util/go_test.go
  cmd/codegen/util/logger.go
  hack/linter.sh
  pkg/apis/jenkins.io/v1/types_environment_test.go
  pkg/config/install_applications_test.go
  pkg/util/json/patch_test.go
Labels: approved, lgtm, size/L

#32 chore: downgrade jsonschema to version in JX
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#33 chore: remove invalid omitempty field
  pkg/apis/jenkins.io/v1/types_release.go
Labels: approved, lgtm, size/XS

#12 chore: verify codegen
  docs/apidocs/openapi-spec/openapiv2.json
  docs/apidocs/openapi-spec/openapiv2.yaml
  jenkins-x.yml
  pkg/client/openapi/core/openapi_generated.go
Labels: approved, lgtm, size/S

#34 chore: port override requirements changes over from JX
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
Labels: approved, lgtm, size/L
