Repository jenkins-x/jx-api, pull requests merged in 2020-11, with the labels that each got.

#75 feat: added in Azure DNS config to requirements so we can configure external dns chart
  pkg/config/install_requirements.go
Labels: approved, lgtm, ok-to-test, size/XS

#76 chore: removed unnecessary indirect imports (that are causing unnecessary downstream mod graph headaches)
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/S

#83 fix: api version for clients
  pkg/apis/core/register.go
  pkg/apis/core/v4beta1/register.go
Labels: approved, size/XS

#84 chore: handle both old and new style jx requirements file
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/test_data/backwards_compatible_requirements_file/new/jx-requirements.yml
  pkg/apis/core/v4beta1/test_data/backwards_compatible_requirements_file/old/jx-requirements.yml
Labels: approved, size/L

#85 chore: add a helper functions to add, update and remove storage URLs
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
Labels: approved, size/M

#86 chore: add a const for the default jx namespace
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, size/XS

#87 refactor: move save and load functions from requirements config to to…
  pkg/apis/core/v4beta1/register.go
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/zz_generated.deepcopy.go
Labels: approved, size/L

#88 chore: tidy up
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/test_data/backwards_compatible_requirements_file/new/jx-requirements.yml
  pkg/apis/core/v4beta1/test_data/get_req_team_settings/boot_requirements.yaml
Labels: approved, size/M

#89 fix: schema generation so we get embedded structs
  go.mod
  go.sum
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/types_environment_test.go
  pkg/apis/core/v4beta1/types_extensions.go
  pkg/util/commands_test.go
  pkg/util/files_test.go
  pkg/util/json/patch_test.go
  pkg/util/urls_test.go
  pkg/util/validation.go
Labels: approved, size/L

#90 feat: lets handle loading old v3 requirments and migrate them to v4
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/test_data/backwards_compatible_requirements_file/new/jx-requirements.yml
  pkg/apis/core/v4beta1/test_data/backwards_compatible_requirements_file/old/jx-requirements.yml
  pkg/apis/core/v4beta1/zz_generated.deepcopy.go
Labels: approved, size/L
