Repository jenkins-x/jx-api, pull requests merged in 2020-09, with the labels that each got.

#51 feat: Added in Azure Vault config to requirements
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, ok-to-test, size/M

#55 feat: Added in config in requirements to store configuration required…
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml
  pkg/config/test_data/jx-requirements.yml
  pkg/config/zz_generated.deepcopy.go
Labels: approved, ok-to-test, size/M

#57 fix: revert "Merge pull request #55 from chrismellard/azure-keyvault-secrets"
  pkg/config/install_requirements.go
  pkg/config/install_requirements_test.go
  pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml
  pkg/config/test_data/jx-requirements.yml
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/M

#61 feat: add in azure secret storage config
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/M

#62 fix: lets use a pointer for the new storage config
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, size/XS

#64 fix: move to use canonical secret name rather than explicit passing
  pkg/config/install_requirements.go
  pkg/config/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/M
