Repository jenkins-x/jx-api, pull requests merged in 2021-01, with the labels that each got.

#106 feat: added azure storage config block
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, lgtm, ok-to-test, size/S

#107 fix: add OCI, kaniko and ingress flags
  go.mod
  go.sum
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, size/M

#108 feat: add a requirement to indicate if we have installed kuberhealthy upfront.
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, size/XS

#109 feat: add Namespace field into EnvironmentConfig
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/test_data/jx-requirements-syntax-error/jx-requirements.yml
Labels: approved, ok-to-test, size/XS

#110 fix: add chart repository type
  pkg/apis/core/v4beta1/requirements.go
Labels: approved, ok-to-test, size/S

#111 fix: lets add a settings configuration
  pkg/apis/core/v4beta1/requirements.go
  pkg/apis/core/v4beta1/requirements_test.go
  pkg/apis/core/v4beta1/settings.go
Labels: approved, size/M

#112 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/XS, updatebot

#113 fix: upgrade k8s
  Makefile.codegen
  go.mod
  go.sum
  hack/update-codegen.sh
Labels: approved, size/L

#114 chore: upgrade go dependencies
  go.mod
  go.sum
Labels: size/S, updatebot
